# Uncomment the next line to define a global platform for your project
platform :ios, ’9.0’

target 'T20Exibition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for T20Exibition
  pod ‘Alamofire’, ‘4.3’
  pod ‘AlamofireImage’, ‘3.2’
  pod ‘SwiftyJSON’
end
